export const atlasTrialCases = [
  {
    id: "trial-001",
    title: "Mercado disciplinario con árbitro detectado",
    partido: "Patriotas vs Jaguares",
    competicion: "Colombia Primera A",
    mercado: "tarjetas",
    lineaMercado: "Más de 4.5 tarjetas",
    cuotaMercado: "1.85",
    uso: "analisis",
    expectedBehavior: [
      "Debe detectar fixture real.",
      "Debe detectar árbitro si está disponible.",
      "Debe marcar sensibilidad arbitral alta.",
      "Debe limitar confianza por falta de histórico arbitral.",
      "No debe emitir apuesta fuerte.",
    ],
  },
  {
    id: "trial-002",
    title: "Mercado de remates con cobertura parcial",
    partido: "Patriotas vs Jaguares",
    competicion: "Colombia Primera A",
    mercado: "remates a arco",
    lineaMercado: "Más de 7.5 remates a arco",
    cuotaMercado: "1.85",
    uso: "analisis",
    expectedBehavior: [
      "Debe detectar estadísticas de remates si están disponibles.",
      "Debe marcar necesidad alta de histórico reciente de equipos.",
      "Debe permitir análisis técnico, pero limitar decisión.",
      "No debe venderlo como pick accionable.",
    ],
  },
  {
    id: "trial-003",
    title: "Mercado no cubierto por API-FOOTBALL",
    partido: "Patriotas vs Jaguares",
    competicion: "Colombia Primera A",
    mercado: "saques de banda",
    lineaMercado: "Más de 35.5 saques de banda",
    cuotaMercado: "1.85",
    uso: "analisis",
    expectedBehavior: [
      "Debe detectar que API-FOOTBALL no cubre saques de banda.",
      "ComplementarySourceCoverage debe bloquear decisión.",
      "DirectorAtlas debe decir no apostar todavía.",
      "No debe generar selección accionable.",
    ],
  },
  {
    id: "trial-004",
    title: "Caso parlay con mercado limitado",
    partido: "Patriotas vs Jaguares",
    competicion: "Colombia Primera A",
    mercado: "tarjetas",
    lineaMercado: "Más de 4.5 tarjetas",
    cuotaMercado: "1.85",
    uso: "parlay",
    expectedBehavior: [
      "Debe ser más estricto que en solo análisis.",
      "Debe bloquear uso en parlay si faltan históricos.",
      "DirectorAtlas debe evitar recomendar parlay.",
    ],
  },
];
